// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// myCindex
double myCindex(NumericVector H, NumericVector time, NumericVector delta);
RcppExport SEXP _mycpp_myCindex(SEXP HSEXP, SEXP timeSEXP, SEXP deltaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type H(HSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type time(timeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type delta(deltaSEXP);
    rcpp_result_gen = Rcpp::wrap(myCindex(H, time, delta));
    return rcpp_result_gen;
END_RCPP
}
// myCindex_smooth
double myCindex_smooth(NumericVector H, NumericVector time, NumericVector delta, double sigma_h);
RcppExport SEXP _mycpp_myCindex_smooth(SEXP HSEXP, SEXP timeSEXP, SEXP deltaSEXP, SEXP sigma_hSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type H(HSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type time(timeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< double >::type sigma_h(sigma_hSEXP);
    rcpp_result_gen = Rcpp::wrap(myCindex_smooth(H, time, delta, sigma_h));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mycpp_myCindex", (DL_FUNC) &_mycpp_myCindex, 3},
    {"_mycpp_myCindex_smooth", (DL_FUNC) &_mycpp_myCindex_smooth, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_mycpp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
