# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

myCindex <- function(H, time, delta) {
    .Call(`_mycpp_myCindex`, H, time, delta)
}

myCindex_smooth <- function(H, time, delta, sigma_h) {
    .Call(`_mycpp_myCindex_smooth`, H, time, delta, sigma_h)
}

